# Full CPU regression after the official two-hour limit

Official run `36813848349` at exact head `39156508f085970a6985b73047f37059178ae488` ended with API conclusion `cancelled`. Its CPU annotation states “The job has exceeded the maximum execution time of 2h0m0s”. The raw CPU log ends after the 73% progress line and cancellation; pytest did not publish a final failure traceback or complete outcome summary. Wheel/CLI and UI completed successfully. Preserve this as incomplete CPU evidence, not a full-suite failure inventory or pass.

Use six deterministic whole-module CPU shards, each retaining the existing 120-minute limit, isolated Python invocation, CPU thread settings, hashed Linux closure, strict independent audit, editable no-deps install/pip check and product types. Matrix fail-fast is disabled so every assigned subset reaches a terminal result. Package and UI commands remain unchanged. Do not remove tests, add skip filters, weaken mathematical/source/runtime gates or change dependency pins.

Every shard first collects the complete suite afresh under the exact candidate and Linux runtime. Fail on collection errors or duplicate node IDs. Partition whole modules deterministically using collected test counts, preserving each module and its internal order. A fresh isolated pytest process must collect exactly its assigned subset. Record full inventory, assignment, source/config identity, runtime versions, terminal pytest status and every selected test's outcome. Write inventory before execution and outcomes atomically during execution, with a nonterminal flag until session completion. Attempt record upload on ordinary failures via the official commit-pinned upload-artifact v7.0.1 action (`043fb46d1a93c77aae656e7c1c64a875d1fc6a0a`; https://github.com/actions/upload-artifact/releases/tag/v7.0.1).

A hard job termination may prevent the trailing upload step; missing artifacts or terminal records mean incomplete execution, never success.

Before claiming full CPU coverage, download all six records and check identical full inventories/source/runtime bindings, pairwise-disjoint assignments whose union is the complete inventory, exact assigned-versus-executed IDs and terminal outcomes, successful execution for each shard, and explicit intentional skips. Local Mac collection counts are not the Linux execution total. The five synthetic fixture portability repairs are included in the new candidate but do not relax production archive certification. Any additional official failures receive separate diagnosis and narrow regressions.

No new official run is dispatched until the helper's synthetic integration checks, workflow checks and GREEN/RED review pass. The next run is recorded at its exact new head. V1 remains open until complete execution and package evidence pass.
