"""Bounded 18-lead 10-minute FV forward execution and time-contract record."""
from __future__ import annotations

import json
import resource
import signal
from time import perf_counter

import torch

from examples.weather_scenarios.fv_long_horizon_case import make_case, make_flow_case


def run() -> dict[str, object]:
    # The research fixture has 4x5 cells. The alarm prevents an accidental
    # unbounded execution if a future change alters stage work substantially.
    signal.alarm(60)
    scenarios: dict[str, object] = {}
    started = perf_counter()
    for name, make in (("zero_flow", make_case), ("nonzero_flow", make_flow_case)):
        built = perf_counter()
        problem, control, parameters = make()
        build_seconds = perf_counter() - built
        forecast_started = perf_counter()
        with torch.no_grad():
            forecast = problem.forecast(control, parameters)
            score = problem.score(control, parameters)
        forecast_seconds = perf_counter() - forecast_started
        transport = problem.frozen.fv_transport
        if transport is None:
            raise ValueError("the long-horizon probe requires FV transport")
        try:
            branch, _ = problem.branch_check(control, parameters)
            branch_probe: dict[str, object] = {
                "status": "passed_at_this_point_without_pinned_endpoint_signature",
                "euler_stages": branch["euler_stages"],
            }
        except ValueError as error:
            branch_probe = {"status": "refused", "reason": str(error)}
        scenarios[name] = {
            "layout": problem.layout,
            "declared_verification_times_seconds": problem.verification_times_seconds,
            "analysis_boundary_steps": len(transport.boundary_echo),
            "future_boundary_steps": len(problem.future_boundary_echo),
            "forecast_shape": list(forecast.shape),
            "strict_branch_probe": branch_probe,
            "max_abs_difference_from_same_operator_synthetic_truth": float(
                (forecast - problem.verification).abs().max()
            ),
            "score_against_same_operator_synthetic_truth": float(score),
            "build_seconds": build_seconds,
            "forecast_and_score_seconds": forecast_seconds,
        }
    signal.alarm(0)
    return {
        "execution_status": "completed",
        "scope": "three regular observations at 0/10/20 minutes; 18 ten-minute forecasts to 200 minutes absolute, 180 minutes after analysis",
        "stationary_flow_and_interval_growth": True,
        "boundary_policy": "constant fully known edges at every SSPRK stage",
        "forecast_available": True,
        "stationarity_passed": "not_tested",
        "local_branch_supported": "see scenario branch probes; no local response is claimed",
        "response_computed": False,
        "response_validation": "not_performed",
        "physical_validation": "not_performed; truth generated by the same discrete operator",
        "scenarios": scenarios,
        "elapsed_seconds": perf_counter() - started,
        "peak_rss_native_units": resource.getrusage(resource.RUSAGE_SELF).ru_maxrss,
    }


if __name__ == "__main__":
    print(json.dumps(run(), indent=2, sort_keys=True))
